### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/fletch#1]
...would be great :smile:

**Comment by kasperl** [comment]
We ended up moving the build instructions to a separate wiki page; see https://github.com/dart-lang/fletch/wiki/Building.

**Comment by kevmoo** [comment]
A request: At least link to the build instructions from the read-me. If someone syncs the code down, they may expect the README to get them going.

**Comment by kasperl** [comment]
The build instructions are linked from the README, but maybe it's too subtle. What we you like to see in the README file?

**Comment by kevmoo** [comment]
I see the "build it" link in the README. Good enough. Thanks!
