### ISSUE TITLE
Multiple list declarations in IDL generated code.

### ISSUE THREAD

**Issue by zerny** [dart-lang/fletch#10]
Using the same list type at several positions results in multiple definitions of the same type in the generated Dart code. For example:

```
struct A {
  List<int32> xs;
}

struct B {
  List<int32> ys;
}
```

results in two declarations of `class _int32List` and `class _int32BuilderList`.

**Comment by madsager** [comment]
Fixed in: https://codereview.chromium.org/927253002/
