### ISSUE TITLE
The fletch process does not correctly exit -15 when receiving a SIGTERM

### ISSUE THREAD

**Issue by ricowind** [dart-lang/fletch#101]
How to reproduce this:
tools/test.py -mrelease -t4 debugger
See that the exit code of the process is 253, when it should be -15 (we send it SIGTERM from test.dart)

**Comment by peter-ahe-google** [comment]
Don't forget to remove TODO from tools/testing/dart/decode_exit_code.dart

**Comment by peter-ahe-google** [comment]
Removing accepted for now to signal that this isn't high priority compared to other accepted bugs in Tools.

**Comment by peter-ahe-google** [comment]
Proposed fix in [CL 1370063002](https://codereview.chromium.org/1370063002/).

**Comment by peter-ahe-google** [comment]
Fixed in 20107997b88fdbf2ce2455948f62fc079db0a138
