### ISSUE TITLE
fletch binary should always exit when it receives a SIGTERM

### ISSUE THREAD

**Issue by ricowind** [dart-lang/fletch#102]
We had a case on the bots ( https://uberchromegw.corp.google.com/i/client.dart.internal/builders/fletch-linux-release-x86/builds/360/steps/Test%20ReleaseIA32Clang/logs/stdio - internal only) where the testing scripts tried to kill the process with SIGTERM. The process did not terminate, and hence we got the watch dog timeout.

**Comment by peter-ahe-google** [comment]
If the process doesn't exit, there's a bug in the persistent process, and it would probably hang instead. I hope that when I fix issue #110, I'll also fix this issue.

I'm closing this bug as there's nothing specific to reproduce here beyond issue #110.
