### ISSUE TITLE
Fletch driver does not support readline.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/fletch#103]
Makes it hard for clumsy fingers to use.

I tried `rlwrap fletch` but it seemed to not work also.

**Comment by sigurdm** [comment]
`rlwrap -a fletch` seems to work somewhat.

**Comment by peter-ahe-google** [comment]
I think this is rather important to get to work.

**Comment by peter-ahe-google** [comment]
I think the solution is to keep canonical processing. If a fletch command needs ICANON input, we should probably have it explicitly request that from the C++ client.

@sgjesse WDYT?

**Comment by peter-ahe-google** [comment]
Proposed solution: [CL 1351643004](https://codereview.chromium.org/1351643004/)

**Comment by sgjesse** [comment]
As mentioned on the CL D8 has some readline support:
https://github.com/v8/v8/blob/master/src/d8-readline.cc
