### ISSUE TITLE
Fletch driver could use a compile-in-fresh-compiler command

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/fletch#105]
For developing on the fletchc compiler it is frustrating to have to kill the fletch resident compiler before running a new compilation.

There could also be a seperate fletchc entrypoint.

**Comment by madsager** [comment]
There was, it was removed.

fletch shutdown is your friend. Easy to script.

**Comment by madsager** [comment]
Sorry, didn't mean to close the issue; reopened.

Instead of a separate entry point, maybe we can add a convenience script to the repo for the compiler devs if this is slowing you down?

**Comment by sigurdm** [comment]
I had not seen the shutdown command. That makes it easier.
I would not say that it slows me down now that I have my own script - but it will slow down anyone else who has to discover it.

**Comment by sigurdm** [comment]
What is the difference between `fletch shutdown` and `tools/persistent_process_info.sh -kill` (if any)?

**Comment by peter-ahe-google** [comment]
Duplicate of issue #122. The proposed solution is to create a test that is easy to run from the command line as well.
