### ISSUE TITLE
corelib/double_parse_test temporarily duplicated

### ISSUE THREAD

**Issue by madsager** [dart-lang/fletch#114]
MacOS's strtod is less precise than the linux version. That causes Fletch to fail two corner case double conversion tests on Mac. That is OK and we want to ignore those failures. For now we have copied corelib/double_parse_test to unsorted/temp_double_parse_test. We are landing a change in the Dart SDK repo that treats these corner cases as a separate test. Once we update the Dart SDK version with that change we should mark only corelib/double_parse_test/02 as failing on mac and remove our local copy.

**Comment by skabet** [comment]
This is reverted for now, so closing issue.
