### ISSUE TITLE
When a test fails with a VM crash it would be useful to print a command line that reruns the test with the VM in gdb.

### ISSUE THREAD

**Issue by ErikCorryGoogle** [dart-lang/fletch#117]
Title is my feature request.

**Comment by peter-ahe-google** [comment]
Proposed fix: (CL 1348193003)[https://codereview.chromium.org/1348193003/]

**Comment by ErikCorryGoogle** [comment]
This looks like a way to run DartVM in gdb, but I was actually looking for a way to run the Fletch VM in gdb.

**Comment by peter-ahe-google** [comment]
This runs the Fletch VM in gdb because it uses follow-fork-mode.
