### ISSUE TITLE
"fletch show help" causes uncaught exception and stack trace

### ISSUE THREAD

**Issue by ErikCorryGoogle** [dart-lang/fletch#120]
I would expect an error message instead, perhaps a pointer to the sorts of "things" that "show" can show information about.

**Comment by peter-ahe-google** [comment]
Proposed fix in [CL 1348763003](https://codereview.chromium.org/1348763003/):

<pre><code>$ <strong>fletch show help</strong>
   show      List things or show information about a thing

$ <strong>fletch compile help</strong>
   compile file FILE
             Compile file named FILE
</code></pre>

I believe we have another bug tracking the fact that show isn't documented.

**Comment by peter-ahe-google** [comment]
Well, I can't find a bug that tracks "show" not being documented, but this CL removes that verb: [CL 1346223003](https://codereview.chromium.org/1346223003).
