### ISSUE TITLE
fletch shutdown does not produce any output

### ISSUE THREAD

**Issue by ErikCorryGoogle** [dart-lang/fletch#121]
It might be helpful to print one of the following messages, to reassure the user that it was not a no-op:

VM closed down on localhost:1234
No VM found on localhost:1234

**Comment by peter-ahe-google** [comment]
I guess I need to improve the documentation of this command.

This shuts down the persistent process, not a Fletch VM.

That being said, we probably also need a command to detach from a Fletch VM that was previously attached. If that command needs to be called `fletch shutdown`, then we'll just have to find a different name for the current `fletch shutdown`.

@lukechurch any thoughts?

**Comment by peter-ahe-google** [comment]
Proposed fix: [CL 1354213003](https://codereview.chromium.org/1354213003/)
