### ISSUE TITLE
Non-persistent version of "out/*/fletch compile-and-run myfile.dart"

### ISSUE THREAD

**Issue by skabet** [dart-lang/fletch#122]
All my current development issues can be solved by a version of 

  out/*/fletch compile-and-run myfile.dart

that doesn't use a persistent process. Preferable, just a flag:

  out/*/fletch compile-and-run --no-persistent myfile.dart

and with a short version as well :)

**Comment by peter-ahe-google** [comment]
Could you give some examples of what problems you have? I think I have an idea, and I'm not sure that "not persistent" is precisely what you need.

**Comment by skabet** [comment]
Basically a mode where the no process is detached, and all VM's launched are a child-process of the entry point (may it be several processes down). Makes sense?

**Comment by peter-ahe-google** [comment]
Yes. Thank you :-)

**Comment by peter-ahe-google** [comment]
We're currently thinking of solving this by having tests that can also be run from the command line. Similar to [feature_test.dart](https://github.com/dart-lang/fletch/blob/a198e667b113a51a5dc486c7be46bf78f06c4905/tests/fletchc/incremental/feature_test.dart), but feature_test.dart should also be generalized to accept files on the command line (for when you don't want to modify [tests_with_expectations.dart](https://github.com/dart-lang/fletch/blob/7d6c8af48e05971fef450a25af5f8367db4b4d9c/tests/fletchc/incremental/tests_with_expectations.dart)).

**Comment by peter-ahe-google** [comment]
Proposed fix in [CL 1307203007](https://codereview.chromium.org/1307203007/)
