### ISSUE TITLE
Add regression test for issue #14

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/fletch#124]
I'm not sure how to test for issue #14, so I'm filing this bug so we don't forget to test it.

It should probably be part of a sanity test we do on our SDK directory.

**Comment by peter-ahe-google** [comment]
@wibling @ricowind Let me know if you have any suggestions.

**Comment by peter-ahe-google** [comment]
Also test that the current directory is respected. The current working directory of the persistent process (Uri.base) is where the first fletch program ran. If the user changes directory, files should be read relative to the client, not the persistent process. This is implemented in [CL 1342673004](https://codereview.chromium.org/1342673004), but not tested yet.

**Comment by mit-mit** [comment]
@peter-ahe-google sounds like we can close this?
