### ISSUE TITLE
Warnings in tests/service_tests/multiple_services/multiple_snapshots_test.cc

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/fletch#125]
tests/service_tests/multiple_services/multiple_snapshots_test.cc:44:3: warning: cannot delete expression with pointer-to-'void' type 'FletchProgram' (aka 'void *') [-Wdelete-incomplete]
  delete programs[0];
  ^      ~~~~~~~~~~~
tests/service_tests/multiple_services/multiple_snapshots_test.cc:45:3: warning: cannot delete expression with pointer-to-'void' type 'FletchProgram' (aka 'void *') [-Wdelete-incomplete]
  delete programs[1];
  ^      ~~~~~~~~~~~
2 warnings generated.

**Comment by madsager** [comment]
I'll steal this one. This should use the API FletchDeleteProgram.
