### ISSUE TITLE
Running 'fletch compile file' defaults to incremental compilation which is currently broken

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/fletch#126]
I was running the fletch-vm on a RPi and attaching to it from my Linux machine. Changing the program and recompiling did not pick up all changes. According to Peter this is most likely caused by incremental compilation not always working.

'fletch compile file' should not default to incremental compilation for now.

**Comment by peter-ahe-google** [comment]
Proposed fix in [CL 1344413002](https://codereview.chromium.org/1344413002/)
