### ISSUE TITLE
gRPC

### ISSUE THREAD

**Issue by floitschG** [dart-lang/fletch#13]
Copied over from http://dartbug.com/22655:
===
see also 

- https://groups.google.com/a/dartlang.org/d/msg/misc/TWYhoawOV_o/hS0eCt6bVAYJ
- http://stackoverflow.com/questions/28860975

**Comment by kasperl** [comment]
Not sure I understand this issue / request? Isn't the original bug a request for gRPC support in Dart and as such not directly related to Fletch?

**Comment by zoechi** [comment]
The issue 22655 was reopened, I guess this can be closed here.

**Comment by floitschG** [comment]
Sorry about that. I was certain I had seen lots of references to fletch in the linked pages.
