### ISSUE TITLE
Create README and LICENSE files for fletch sdk bundle

### ISSUE THREAD

**Issue by ricowind** [dart-lang/fletch#144]
We need a README and LICENSE file for our sdk bundle:
@mit-mit @anders-sandholm something for you?

Blocking: #140

**Comment by mit-mit** [comment]
I think that is me, lets chat tomorrow

**Comment by mit-mit** [comment]
@ricowind, this works for license:
https://github.com/dart-lang/fletch/blob/master/LICENSE.md

For readme, I suggest we simply point users at http://dart-lang.github.io/fletch/

**Comment by ricowind** [comment]
The top comments in:
https://github.com/dart-lang/fletch/blob/master/LICENSE.md
is not correctly reflecting what will be in the bundle
