### ISSUE TITLE
ctrl+d in the debugger makes us crash and dump a core

### ISSUE THREAD

**Issue by ricowind** [dart-lang/fletch#147]
How to reproduce this:
out/ReleaseIA32/fletch compile-and-run test.dart
ctrl+d

What is the expected outcome:
  exits the program cleanly

What is the actual outcome:
 ```
> Failed to read from socket
Non-zero exit code from 'out/ReleaseIA32/fletch-vm' (-6).
Aborted (core dumped)
```

**Comment by ricowind** [comment]
cc @madsager @wibling @peter-ahe-google

**Comment by peter-ahe-google** [comment]
I think this is the debugger session (session.dart) that terminates the VM incorrectly.

**Comment by peter-ahe-google** [comment]
I had the same issue in feature_test.dart at some point. Should be too hard to fix.
