### ISSUE TITLE
Don't invoke tearoffs when invoking closurized fields

### ISSUE THREAD

**Issue by skabet** [dart-lang/fletch#153]
Example:

  bar(a) {
    return a is String;
  }
  var bar_tearOff = bar.call;
  bar_tearOff.call();

Will do stack-overflow because we'll continue to invoke 'call' tearoff.

**Comment by peter-ahe-google** [comment]
We're going to need a bigger stack ;-)

**Comment by kasperl** [comment]
Fixed in https://github.com/dart-lang/fletch/commit/d522da622980eb1d9446557ff9787202ff646b63.
