### ISSUE TITLE
Move .fletch to $HOME

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/fletch#154]
The persistent process should store its "configuration" file in $HOME.

**Comment by kasperl** [comment]
Are we going to version the .fletch file so we can automatically shutdown an out-dated persistent process?

**Comment by peter-ahe-google** [comment]
We need to do something. Short term we really need to move .fletch to a known location. Using the SDK directory wont work as you're supposed to be able to install it in /usr/.

One possibility is that we include the version number in the .fletch file's name (only for sdk releases, for developer builds, I think we should use a fixed name).

In addition, I'd like to figure out if we can automatically shut down the background process. We probably need separate bugs for all these things (which I can file before I close this bug).

**Comment by ErikCorryGoogle** [comment]
Could we shut it down as part of gclient runhooks?  I can't see any situation where you would want to do runhooks and then continue to use the persistent process from before.

And how about when we write a new fletch-vm?

**Comment by peter-ahe-google** [comment]
I think this bug is about our users. For us Fletch developers, we already shut down the persistent process as part of running tests.

**Comment by peter-ahe-google** [comment]
I've implement this:

First look for $FLETCHRC which will be the name of the configuration (socket file).

If $FLETCHRC isn't defined, use "$HOME/.fletch" (if $HOME isn't defined, use getpwuid_r).

See [CL 1373773005](https://codereview.chromium.org/1373773005).

**Comment by peter-ahe-google** [comment]
Changed the name from `FLETCHRC` to `FLETCH_SOCKET_FILE`.
