### ISSUE TITLE
Version number support in snapshots

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/fletch#157]
We should write a version number into snapshots to ensure that they can only be run with versions of the VM that they are compatible with

**Comment by mkustermann** [comment]
I think that is a good idea. Additionally, we might also want to ensure that the protocol spoken between the persistent process and a (possibly remotely running / embedded) fletch-vm also communicates in a supported version (and not just crash).

**Comment by peter-ahe-google** [comment]
Blocks #157.

**Comment by cpu-chromium** [comment]
+1
