### ISSUE TITLE
fletch command hangs after being stopped and restarted

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/fletch#161]
Repro steps:

Create repro.dart:
```
main() {
  while (true) {
    print("hello");
  }
}
```

Run it:
```fletch run repro.dart```

Kill by pressing ```CTRL-C```

Run it:
```fletch run repro.dart```

Actual result: Hangs
Expected result: Just runs again

This is really annoying when doing a "fix bug and run it again" cycle.

**Comment by peter-ahe-google** [comment]
Gustav has a fix for this in [CL 1384703002](https://codereview.chromium.org/1384703002/)
