### ISSUE TITLE
Clean up bin/ in SDK (remove natives.json)

### ISSUE THREAD

**Issue by kasperl** [dart-lang/fletch#164]
How many of the files in bin/ are useful to end-users? 

```
  bin/fletch-sdk.packages
  bin/fletch
  bin/fletch-vm
  bin/natives.json
  bin/fletch-agent.snapshot
```

Can we get it down to one or two? Clearly we need `fletch`, but I guess the only reason why we have `fletch-vm` in there is if our users want to start from a snapshot? Maybe it would be easier to grok if it was called `fletch-run-snapshot` in that context?

**Comment by peter-ahe-google** [comment]
It should be fine to have only `fletch` and `fletch-vm` in `bin`. I see the attraction of renaming `fletch-vm`, but I also think it serves a purpose as a standalone program you can explicitly connect to. So my inclination is to keep the name.

**Comment by kasperl** [comment]
I think we'll find lots of people who will try to run `fletch-vm hello.dart` as their first program. At least I know of more than one who has already tried that.

**Comment by peter-ahe-google** [comment]
Perhaps we should fix that by producing a sensible error message?

**Comment by sgjesse** [comment]
The `bin/fletch-agent.snapshot` file is now removed.

**Comment by sgjesse** [comment]
As for `bin/natives.json` is that used by the compiler? If so where should it be?

**Comment by mit-mit** [comment]
Min bar for launch is at least splitting into two:

Keep in bin:
```
bin/fletch
bin/fletch-vm
```

Move to something internal.
```
bin/natives.json
```
