### ISSUE TITLE
Fletch Raspberry Package should reconfigure the green LED to be available over GPIO

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/fletch#166]
This simply entails executing this command:
```
echo none | sudo tee /sys/class/leds/led1/trigger
```

This is needed by the /samples/basic/blinky.dart program.

**Comment by wibling** [comment]
I assume this is something you would want us to add to the boot process of the pi2? I'll take a look.

**Comment by sgjesse** [comment]
Added a Raspberry Pi library with access to the two LEDs in https://github.com/dart-lang/fletch/commit/6938d6c9b89b5b18eaa5c860e297ed59c271c1b1.
