### ISSUE TITLE
Create samples/hello.dart

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/fletch#173]
Create simple hello.dart program that says ```hello from <sysinfo>``` where sysinfo is from https://codereview.chromium.org/1381993003/

**Comment by kasperl** [comment]
Is this the `hello.dart` program referred to in the launch doc?

**Comment by mit-mit** [comment]
Yup.

**Comment by mit-mit** [comment]
CL: https://codereview.chromium.org/1384663003/
