### ISSUE TITLE
Making it easy to manually run debugger tests and update expectation files.

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/fletch#182]
The change 995b40aac63610d1b4e5f0707a9e88a319c34035 caused us to loose a way of quickly reproducing debugger test expectation mismatch.

Previously `./tools/test.py` provided a simple reproduction command, like this:
```
$ out/DebugIA32/fletch compile-and-run --test-debugger=r,q tests/debugger/unsupported_hint_test.dart
```
So one could easily update the expectation file.

Now the output of `./tools/test.py` is not useful anymore and it became much harder to produce a new expectation file:
```
  Command[fletch_test]: FletchTestCommand(debugger/unsupported_hint_test)
```

Maybe we can have a small shell script, or something like that, that uses `fletch debug` with the correct debugging commands to reproduce test failures?

cc: @peter-ahe-google

**Comment by mkustermann** [comment]
What makes this much worse is that the debugger output uses tab characters (i.e. '\t' characters). Using copy&paste with mouse seems to make them spaces. This is really bad!

**Comment by madsager** [comment]
#!/bin/bash

FLETCH_DIR=/home/ager/ssd/fletch-repo/fletch

cd $FLETCH_DIR

./out/ReleaseIA32/fletch shutdown;

for file in `ls tests/debugger/*_test.dart`;
do
    echo $file
    TEST_DEBUGGER=`grep "FletchDebuggerCommands=" $file`
    if [ -n "$TEST_DEBUGGER" ]; then
        TEST_DEBUGGER="${TEST_DEBUGGER/\/\/ FletchDebuggerCommands/}"
    fi
    EXPECTATION_FILE="${file/_test.dart/_expected.txt}";
    ./out/ReleaseIA32/fletch compile-and-run $file "--test-debugger$TEST_DEBUGGER" > $EXPECTATION_FILE;
done

**Comment by madsager** [comment]
I have used the above script to rebaseline debugger tests in the past. It was something I put together very quickly and I don't know if it still works so YMMV.

Feel free to change the debugger to not use tabs.

**Comment by madsager** [comment]
Oh, I see, we removed compile-and-run and I haven't been following the changes in connection with that. So I don't know what the right replacement is in the script above.

**Comment by mkustermann** [comment]
I'm running into this issue quite often and am impatient. I'll take it over.

**Comment by mkustermann** [comment]
This has been fixed for a while. One should be able to generate new golden files via:
```
$ ./out/DebugIA32/dart -Dfletch.version=`out/DebugIA32/fletch-vm --version`  tests/debugger/debugger_tests.dart             
```
