### ISSUE TITLE
Event loop not running after prompting for remote IP address

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/fletch#186]
When fixing #177 the code to prompt for IP address will say that the eventloop was started, but that's only for a short while as the compiler may run later. This should be revisited.

**Comment by wibling** [comment]
Isn't this fixed now with your no signal processing when entering IP change?

**Comment by peter-ahe-google** [comment]
Fixed in acce3c68bdd7740d4ac465e5db277292617b355d
