### ISSUE TITLE
The generated remote.fletch-settings have "null" in "packages"

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/fletch#189]
Using the [latest SDK](http://storage.googleapis.com/fletch-archive/channels/be/raw/0.1.0-edge.5015466f60b9f4a468500e346ead47efdd9e28d8/sdk/fletch-sdk-linux-ia32-release.zip), and running

```
$ bin/fletch run samples/raspberry_pi/basic/blinky.dart in session remote
```

Enter `pi3` when asked `Please enter IP address of remote device:`.

The created `remote.fletch-settings` have `"null"` (in quotes), and not just `null`:

```
{
  "packages": "null",
  "options": [],
  "constants": {},
  "device_address": "pi3:12121"
}
```

**Comment by peter-ahe-google** [comment]
I cannot reproduce this problem.

**Comment by peter-ahe-google** [comment]
I can repro, and have a fix.

**Comment by peter-ahe-google** [comment]
Proposed fix: [CL 1384253005](https://codereview.chromium.org/1384253005/)

**Comment by peter-ahe-google** [comment]
In order to reproduce this, I had to delete `fletch-sdk/internal/fletch-sdk.packages`.

**Comment by sgjesse** [comment]
I don't know how I ended up in this situation. I had unpacked an SDK from the bot. I still had it in a temp directory. Removing `remote.fletch-settings` and running

```
$ bin/fletch run samples/raspberry_pi/basic/blinky.dart in session remote
```

again created this `remote.fletch-settings`

```
{
  "packages": "file:///tmp/fletch-sdk/fletch-sdk/internal/fletch-sdk.packages",
  "options": [],
  "constants": {},
  "device_address": "pi3:12121"
}
```

Running

```
$ ls -l internal/
```

Gives (with user and group renamed);

```
total 11504
-rwx------  1 uuu xxx 11740984 Oct  4 16:01 dart
drwx------  3 uuu xxx     4096 Oct  4 16:01 dart_lib
drwx------  3 uuu xxx     4096 Oct  4 16:01 fletch_lib
-rw-------  1 uuu xxx      161 Oct  4 16:01 fletch-sdk.packages
-rw-------  1 uuu xxx    18534 Oct  4 16:01 natives.json
drwx------ 13 uuu xxx     4096 Oct  4 16:01 pkg
```

so `internal/fletch-sdk.packages` seemed to have been there all along.

**Comment by sgjesse** [comment]
Tried with a clean 0.1.0-dev.5.0. No problems. Created a `$HOME/remote.fletch-settings` which points to the correct `fletch-sdk.packages`.
