### ISSUE TITLE
Our documentation needs to work around issues decompressing Raspbian image

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/fletch#193]
The binaries from here: https://www.raspberrypi.org/downloads/raspbian/ don't decompress with the tools installed by default on OS X. Our documentation needs to explain the work arounds (e.g. User The Unarchvier)

Even though this doesn't feel like it's our problem the user impact is noticeable enough that we need to document the work around.

**Comment by lukechurch** [comment]
The GUI tool decompresses it to a cpgz file. The command line tool reports
```
 "skipping: 2015-09-24-raspbian-jessie.img need PK compat. v4.5 (can do v2.1)"
```

**Comment by lukechurch** [comment]
This only appears to impact the Jessie image, the Wheezy file seems to be ok.

**Comment by ricowind** [comment]
You can do:
```
ditto -x -k 2015-09-24-raspbian-jessie.zip .
```
instead of using unzip, which is installed by default on newer OS X's

**Comment by mit-mit** [comment]
Done, https://codereview.chromium.org/1383673003/
