### ISSUE TITLE
Sending SIGINT to Raspbian (wheezy) is ignored by the spawned fletch-vm

### ISSUE THREAD

**Issue by wibling** [dart-lang/fletch#195]
For some reason SIGINT seems to be ignored when send to a detached spawned fletch-vm process on Raspbian wheezy. It does not happen on Raspbian jessie, but we should find out why there is this difference in behavior.

**Comment by peter-ahe-google** [comment]
Did you discover the reason for the difference in behavior?

**Comment by wibling** [comment]
No I didn't spend that much time on it. Since it is an old platform it didn't seem worth spending too much time on.
