### ISSUE TITLE
Support automatic discovery of remote devices e.g. using multicast

### ISSUE THREAD

**Issue by wibling** [dart-lang/fletch#225]
Support some kind of discovery protocol for detecting what devices are available.

**Comment by mit-mit** [comment]
Tentatively tagging for 0.1.1

**Comment by sgjesse** [comment]
Planning on starting out with mDSN for finding the IP of the remote device.

**Comment by sgjesse** [comment]
Implementation of an mDNS approach has been finalized.

1. The Dart VM `mdns` package adds support for service discovery
2. The fletch agent Debian package adds the `service _fletch_agent._tcp.local` the the Avahi daemon configuration
3. The fletch compiler support the command `x-discover` and discovery when selecting a remote device
