### ISSUE TITLE
Avoid complaining about missing externals in dart:mirrors

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/fletch#233]
As we already print a message like this:

    Error: Fletch doesn't support 'dart:mirrors'. See https://goo.gl/Kwrd0O

We don't need to print these errors:

```
third_party/dart/sdk/lib/mirrors/mirrors.dart:147:25:
Error: External method without an implementation.
external InstanceMirror reflect(Object reflectee);
                        ^^^^^^^
```

Simplest solution is probably just to provide the external methods and have them throw.

**Comment by sigurdm** [comment]
This will be fixed by https://codereview.chromium.org/1496243004/
