### ISSUE TITLE
Text for uncompress archive on OS X needs a box

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/fletch#236]
The code text here: http://dart-lang.github.io/fletch/ is generally in boxes. That's great.

The commands under "Step 1: Raspbian operating system" should also be in boxes. This will make it easier to copy and paste.

Study Participant 2 missed the tailing '.' when copying and pasting the command for uncompressing the zip file on Mac

**Comment by mit-mit** [comment]
This was fixed a while back:
http://dart-lang.github.io/fletch/
