### ISSUE TITLE
Provide guidance for which SDK to download

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/fletch#237]
http://dart-lang.github.io/fletch/ currently reads: "pick the one that matches the OS of the PC you will be using for development:"

Almost all of our users are using 64 bit machines, OS X users often pause whilst they try and remember which one to download.

We should use the same auto adaption from dartlang.org code to select what we think is 'probably the right link' for the user, and offer the others as secondary options.

If there are good reasons why the user should consider picking a different distribution than their machine architecture, e.g. performance, we need to work out what these reasons are and make them clear on the page.

(From Participants 1 and 2)

**Comment by mit-mit** [comment]
Closing, we removed the 32-bit links as they were a mix of 32 and 64 bit anyway.
