### ISSUE TITLE
Sample demo code to show how callback mechanism in fletch.

### ISSUE THREAD

**Issue by DanCraft99** [dart-lang/fletch#24]
there are two new ways of interfacing mechanisms to third party layers, the first is ffi and the other is idl interface bindings. Please help provide sample code on how to implement callback for the following cases

1) ffi
Fletch calls the third party c api, and registers a callback function for third party api to callback.

2) idl interface service
The third party provide a callback function to fletch, and fletch calls the third party callback.

If two way event handling are possible for both ffi and idl service, it is good with an example code.
Thanks.

**Comment by kasperl** [comment]
I will try to write up a few samples. Thanks for reporting / requesting this!

**Comment by peter-ahe-google** [comment]
@kasperl ping :-)

**Comment by mit-mit** [comment]
We don't currently support call backs. We opened #351 351 to track that.
