### ISSUE TITLE
tests/unsorted/dart2js_hello_world_test.dart, etc fails with `fletch run`

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/fletch#254]
`fletch run` needs to start the fletch-vm in the current directory of the C++ client, not in `/`.

**Comment by peter-ahe-google** [comment]
@wibling be aware of this issue in relation to the Fletch Agent.

**Comment by wibling** [comment]
I will file another bug for the agent. I see it as a different issue since the user will not/should not expect a specific working directory when running on a Raspberry PI with a fletch-vm launched by the agent.

**Comment by wibling** [comment]
Btw. isn't this fixed by your recent change https://codereview.chromium.org/1415153006/?

**Comment by peter-ahe-google** [comment]
Dupe of #282
