### ISSUE TITLE
Same-named service and struct cause servicec to generate invalid code

### ISSUE THREAD

**Issue by smanilov** [dart-lang/fletch#256]
Consider the following:

```
service Foo {
}

struct Foo {
    int32 foo;
}
```

This will result in C++ output containing:

```C++
class Foo {
   ...
}

class Foo : public Reader {
   ...
}
```

Dart output containing:

```dart
abstract class Foo {
    ...
}

class Foo extends Reader {
    ...
}
```

and Java output containing only a file generated for the `service`, but not for the `struct` (`Foo.java`, of course).

Correct behaviour would be to generate unique class names.

**Comment by smanilov** [comment]
Regression because of https://github.com/dart-lang/fletch/issues/234

**Comment by zerny** [comment]
How about we let the definition of "service Foo { ... }" be "class FooService { ... }". The struct definitions will keep the same name. We should then add a check such that "struct FooService { }" is considered invalid.

**Comment by smanilov** [comment]
Resolved in https://github.com/dart-lang/fletch/commit/5bf1afe1b70ecf07efe349caede4390c727e5bbc
