### ISSUE TITLE
Build a Raspbian image prepared for fletch

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/fletch#261]

**Comment by sgjesse** [comment]
First step in https://github.com/dart-lang/fletch/commit/953331e2973be2ffb22ab1e2a06c192b8f342d3d.

**Comment by ricowind** [comment]
The bots are now archiving raspbian images with the fletch vm and agent preinstalled.
In addition, the image is prepared for being setup with the platforms/raspberry-pi2/flash_sd_card command
