### ISSUE TITLE
Crash: Non-immutable closure allocated with AllocateImmutable

### ISSUE THREAD

**Issue by kasperl** [dart-lang/fletch#273]
Looks like the Fletch runtime crashes on this code because it believes the closure `() => T` is immutable, but it really isn't. It looks like we expect more on the expression stack in the immutable case, but since we haven't provided those values we end up using a return address (a bytecode pointer) and depending on the alignment of that we consider it a smi or an object pointer. If it's an object pointer, we crash. The code below fails, but if you add `var x = 0;` before the `new A();` statement it passes because the return address moves by one.

We generally don't actually deal with type variables, but this crashes not when calling the closure but rather when allocating it.

```
class A<T> {
  var t;
  A() : t = (() => T);
}

main() {
  new A();
}
```

**Comment by skabet** [comment]
Should be fixed in f85fea1becc21a15242f0d8894f8fae6a9df3aa6.
