### ISSUE TITLE
Uri.base does not give meaningful results with fletch run.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/fletch#282]
I have the program: ~/test/main.dart:
```
main(args) {
  print(Uri.base);
}
```
And run:
```
$ pwd
/usr/local/google/home/sigurdm/projects/fletch-repo/fletch

$  out/ReleaseX64/fletch run ~/test/main.dart
file:////
```
It seems the fletch-vm process is run with '/' as working directory, and appends another '/' to it.

**Comment by peter-ahe-google** [comment]
Proposed fix: [CL 1415153006](https://codereview.chromium.org/1415153006)
