### ISSUE TITLE
platforms/raspberry-pi2/flash_sd_card ate my /tmp dir

### ISSUE THREAD

**Issue by ricowind** [dart-lang/fletch#284]
I ran:
platforms/raspberry-pi2/flash_sd_card --sd-card=/dev/sdc --skip-download --zip-file=/usr/local/google/home/ricow/Downloads/fletch_raspbian.img.zip

If failed with:
This program will prepare an SD card for the Raspberry Pi 2
Using the SD card /dev/sdc. Press enter to use this card. This will delete all contents on the card.
Enter the name of the device - default is 'fletch': 
Enter the static IP address you would like the device to have. Leave it blank to have it assigned via DHCP:
Skipping download
Decompressing SD card image.
Unmounting the SD card.
Writing image to SD card.
Writing: DONE
Failed to write SD card
dd: failed to open ‘/tmp/2015-09-24-raspbian-jessie-fletch-0.1.0-edge.9b6223bf6327d91e42681db8c8a9894d057089d5.img’: No such file or directory

Mounting the SD card.
Running sync
Finished flashing the SD card. You can now insert it into the Raspberry Pi

and now my /tmp directory is gone

**Comment by sgjesse** [comment]
Fixed in https://github.com/dart-lang/fletch/commit/7fdaea8528cc061e2ffbc999cd4b528954076e87.
