### ISSUE TITLE
Download link from bots is http not https

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/fletch#287]
This is at least the case for the Fletch Raspbian image:

@@@STEP_LINK@download@http://storage.googleapis.com/fletch-archive/channels/be/raw/0.1.0-edge.d8cabb9332b9a1fb063f55fca18d8b87320e863a/sdk/fletch_raspbian.img.zip@@@

We should change that to https.

**Comment by ricowind** [comment]
This has been fixed a while ago
