### ISSUE TITLE
Object.toString() should print classId

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/fletch#290]
Currently Object.toString returns "[object Object]". The ideal would be to return something like
"instance of $runtimeType".
Even without runtimeType support in fletch it would be nicer to return "instance of class with class id $classId".

**Comment by peter-ahe-google** [comment]
Short term, I'd vote for: "Instance of class#$classId".

But most importantly, it should something that @mkustermann's program for decoding errors can understand.

**Comment by mit-mit** [comment]
Dupe of #29
