### ISSUE TITLE
Assertion error in VM.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/fletch#291]
To reproduce, replace FletchNoSuchMethodError.toString in lib/system/nsm.dart with:
```
  String toString()  => 'FletchNoSuchMethodError($_receiver, $_receiverClass, selector: $_receiverSelector)';
```
And run
```
main(args) {
 try {
   new Object().fisk();
 } catch (e) {
   print(e);
 }
}
```
With the debug build of fletch.
Output:
```
Warning: No method named 'fisk' in class 'Object'.
   new Object().fisk();
   ^^^^^^^^^^^^^^^^^^^
../../src/vm/object.h:1553: error: expected: object->IsArray()
fish: Job 1, “out/DebugX64/fletch run ~/test/main.dart” terminated by signal SIGABRT (Abort)
```

**Comment by mit-mit** [comment]
@skabet is this relevant?

**Comment by skabet** [comment]
@sigurdm, can you confirm we fixed it that day?

**Comment by sigurdm** [comment]
I think we found out that printing _receiverClass crashes the fletch vm. I am not sure if that is considered ok because it cannot happen from user code.

**Comment by skabet** [comment]
Yes, that was it. And yes, that is ok. We haven't implemented that yet, and it's not exposed to the user. Closing.
