### ISSUE TITLE
Printing a list of strings exhibits sub-optimal perfomance

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/fletch#30]
Repro: Print a list of 10,000 strings that look approximately like
"nnnnnnnnnnnnn, nnnnnnn, -nn, nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn, n, nnnn"
and pipe the results into a file.

Some timing results, OS X 10.10.3, SSD
	Dart 64bit VM: 15ms
	Fletch Release 32bit: 17,454ms
	Fletch Debug 32bit: 295,545ms

This seems a little tardy.

**Comment by skabet** [comment]
I'll take a look.

**Comment by skabet** [comment]
With Mads' hashCode change, I now see the following:

main() {
  var l = [];
  for (int i = 0; i < 10000; i++) {
    l.add("fsdfsdf");
  }
  print(l);
}

Dart VM: 0m0.126s
Fletch VM: 0m0.480s
