### ISSUE TITLE
Review the version conflict message between the compiler and the fletch command

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/fletch#307]
If the persistent process (compiler) and the fletch command have different versions this message is displayed:

```
Connection rejected because running compiler and SDK have different versions.
Compiler version: '0.2.0-edge.a83b43778a51e6a3c8ee639e6c03886b8d10a376'
SDK version: '0.2.0-dev.3.0'.
Try running 'fletch quit' and retry the command.
```

Is the distinction between SDK and compiler something people can understand?

This typically only happens when upgrading - should that be part of the message?

**Comment by lukechurch** [comment]
As discussed, no, I didn't understand.

In this case lets rename SDK to 'Fletch Command Line Interface (CLI)'.

Possibly also add, "this can happen if you've recently updated Fletch. Try running 'fletch quit' and retry the command."
