### ISSUE TITLE
Confusing fletch quit interaction

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/fletch#310]
```
lukechurch-macbookpro:fletch-sdk lukechurch$ ./bin/fletch --version
0.1.0-dev.6.0
lukechurch-macbookpro:fletch-sdk lukechurch$ ./bin/fletch quit
Background process wasn't running
lukechurch-macbookpro:fletch-sdk lukechurch$ ./bin/fletch --version
0.2.0-dev.3.0
```

This was during an upgrade.
As fletch quit reported "Nothing was running for me to quit", it's unclear why the reported version changed on re-execution.

**Comment by sgjesse** [comment]
Can this be caused by a compiler from before the version was communicated from the CLI?

**Comment by wibling** [comment]
I suspect this is due to the way we detect which persistent process is
running. Peter mentioned something about the background process socket file
changing when upgrading meaning the new sdk would not find the old process.
I am not sure but I will try to repro and see if it makes sense.

**Comment by peter-ahe-google** [comment]
This is what happens:

1. We use lsof to find processes using the Dart VM binary bundled in the SDK. There are no such processes.

2. We don't kill any process, but still delete the socket file. The persistent process is still running, but nobody can contact it.

3. Next time you run `fletch ...` a new persistent process is started. This process creates a new socket file.

**Comment by wibling** [comment]
What Peter said ;) I seem to be able to reproduce this, so I will look into
using pgrep instead of lsof to determine whether an existing persistent
process is running.

/gustav

On Thu, Nov 12, 2015 at 1:34 PM, Peter von der Ahé <notifications@github.com
