### ISSUE TITLE
String.Split isn't implemented

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/fletch#32]
And is pretty important for any string processing. I suspect it isn't implemented because of a dependency on regex.

I have built a dumb work around, lets decide what the strategy is here.

**Comment by skabet** [comment]
Would a implementation only accepting Strings as pattern be okay for now?

**Comment by madsager** [comment]
An implementation only accepting String patterns would be a great start. Most of my usages of String.split are with String patterns.

(Sorry about the accidental close and reopen).

**Comment by lukechurch** [comment]
@skabet Yes that would be a great start, split by string patterns would cover almost all of my usages.

**Comment by skabet** [comment]
Landed in 0fce100. Let's open a new CL for overall RegExp support.
