### ISSUE TITLE
Enable the user to see warnings in a package they are developing

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/fletch#338]
I'm developing a new package. This includes a small sample that uses the package. Often when I run the sample program, Fletch me that there are suppresed warnings in the package:

```
$ ./out/ReleaseX64/fletch run pkg/mqtt/subscribe-sample.dart 
Hint: 12 warning(s) suppressed in package:mqtt.
```

It would be great to have a way of seeing those.

**Comment by kasperl** [comment]
For now, I think I'd be happy with always showing all warnings -- and we can achieve that by adding '--show-package-warnings' to the `EXTRA_DART2JS_OPTIONS` list:

https://github.com/dart-lang/fletch/blob/master/pkg/fletchc/lib/src/fletch_compiler_implementation.dart#L65

**Comment by mit-mit** [comment]
Yes, that works great. Iff we want a flag on the fletch, I think the default should be to show these and then have a suppress flag.
