### ISSUE TITLE
"Bad stackSize for return bytecode: 0" message on compiling code with futures

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/fletch#36]
I know this feature isn't supported, but we need an error message explaining that, rather than something that looks like a tool crash

../dart/sdk/lib/async/async_error.dart:17:10:
Internal Error: The compiler crashed when compiling this element.
Function _registerErrorHandler(Function errorHandler, Zone zone) {
         ^^^^^^^^^^^^^^^^^^^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

Unhandled exception:
Uncaught Error: Bad stackSize for return bytecode: 0
Stack Trace:
#0      BytecodeBuilder.ret (package:fletchc/src/bytecode_builder.dart:294:25)
#1      CodegenVisitor.generateReturn (package:fletchc/src/codegen_visitor.dart:325:16)
#2      CodegenVisitor.visitReturn (package:fletchc/src/codegen_visitor.dart:2097:19)
#3      Return.accept (package:compiler/src/tree/nodes.dart:1075:49)
#4      CodegenVisitor.handleStatements (package:fletchc/src/codegen_visitor.dart:2053:23)
#5      CodegenVisitor.visitBlock (package:fletchc/src/codegen_visitor.dart:2073:21)
#6      Block.accept (package:compiler/src/tree/nodes.dart:598:48)
#7      CodegenVisitor.visitIf (package:fletchc/src/codegen_visitor.dart:2169:25)
#8      If.accept (package:compiler/src/tree/nodes.dart:624:45)
#9      CodegenVisitor.handleStatements (package:fletchc/src/codegen_visitor.dart:2053:23)
#10     CodegenVisitor.visitBlock (package:fletchc/src/codegen_visitor.dart:2073:21)
#11     Block.accept (package:compiler/src/tree/nodes.dart:598:48)
#12     FunctionCodegen.compile (package:fletchc/src/function_codegen.dart:97:23)
#13     FletchBackend.codegenFunction (package:fletchc/src/fletch_backend.dart:748:22)
#14     FletchBackend.codegen.<anonymous closure> (package:fletchc/src/fletch_backend.dart:705:24)
#15     Compiler.withCurrentElement (package:compiler/src/compiler.dart:904:15)
#16     FletchBackend.codegen (package:fletchc/src/fletch_backend.dart:704:34)
#17     Compiler.codegen (package:compiler/src/compiler.dart:1837:20)
#18     CodegenWorkItem.run (package:compiler/src/compiler.dart:218:21)
#19     Compiler.processQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:1734:54)
#20     Compiler.withCurrentElement (package:compiler/src/compiler.dart:904:15)
#21     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:1734:25)
#22     QueueFilter.processWorkItem (package:compiler/src/enqueue.dart:913:6)
#23     Enqueuer.forEach (package:compiler/src/enqueue.dart:608:31)
#24     Compiler.processQueue (package:compiler/src/compiler.dart:1733:18)
#25     Compiler.compileLoadedLibraries (package:compiler/src/compiler.dart:1671:17)
#26     Compiler.runCompiler.<anonymous closure> (package:compiler/src/compiler.dart:1505:29)
#27     _RootZone.runUnary (dart:async/zone.dart:1155)
#28     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:484)
#29     _Future._propagateToListeners (dart:async/future_impl.dart:567)
#30     _Future._completeWithValue (dart:async/future_impl.dart:358)
#31     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:412)
#32     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#33     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)

**Comment by skabet** [comment]
We now get the following error:

$ fletchc_driver stuff.dart 
../dart/sdk/lib/core/regexp.dart:127:3:
Error: External function is not supported
  external factory RegExp(String source, {bool multiLine: false,
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compile error
Non-zero exit code from '/usr/local/google/home/ajohnsen/src/fletch/fletch/out/DebugX64Clang/fletch' (254).
