### ISSUE TITLE
typed_data/typed_data.dart : Float64List not implemented

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/fletch#38]
This is a little surprising given that the other parts of the library seem fairly well covered

**Comment by lukechurch** [comment]
Int32x4 is also missing

**Comment by skabet** [comment]
Only Uint8List is in at this point. I'll add the remaining once we are happy about dart:ffi.

**Comment by mit-mit** [comment]
@wibling didn't you look at this area before? Tagging as FixIt candidate.

**Comment by wibling** [comment]
I added support for uint16List and uint32List. Are you suggesting I spent some time adding the rest:)

**Comment by skabet** [comment]
Yes :)

**Comment by wibling** [comment]
This is is fixed in commit b4d68efd850dc7be57eb5030614e0ea39571a940
