### ISSUE TITLE
TransformInstances is not iterating all processes

### ISSUE THREAD

**Issue by madsager** [dart-lang/fletch#51]
When transforming instances because of interactive program changes we need to iterate through all process heaps. This is done in Session::TransformInstances. However, TransformInstances only looks at processes in the session and in the scheduler. There can be processes that are not know to the scheduler because they are not currently active but which are referenced from ports in other processes heaps. We need to take those into account as well in the same way we do when performing a full Program GC.

**Comment by mkustermann** [comment]
Should be fixed now.
