### ISSUE TITLE
Document how to roll a new version of Dart

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/fletch#61]
Ultra short version is:

Checkout this branch:

https://github.com/dart-lang/sdk/tree/_temporary_fletch_patches

Identify the commit on the master branch you want, often just:

```git rev-parse origin/master```

Merge this commit into _temporary_fletch_patches using --no-edit:

```git merge -X theirs --no-commit COMMIT_ID```

Make the diff is empty:

```git checkout COMMIT_ID -- .```

Verify that the diff is empty:

```git diff COMMIT_ID```

Commit the merge:

```git commit --no-edit```

## Identify the patches needed

Use this command to find the last merge:

<pre>$ <strong>git log --oneline --merges origin/master.._temporary_fletch_patches</strong></pre>

This will produce output like this:

```
e4f708a Merge commit 'f4075e6bad47da89433eac6bfbed444cc5f926a4' into _temporary_fletch_patches
5972121 Merge commit '253ffeed4a7e27a4085f63aa6d60e8c19f3454d5' into _temporary_fletch_patches
1170e81 Merge commit '9f00e0591816edd4cca0cf349e87b7b4f82cd2e6' into _temporary_fletch_patches
23736d3 Version 1.11.0-dev.5.2
01a361f Version 1.11.0-dev.5.0
c8d21bc Version 1.11.0-dev.4.0
6072062 Version 1.11.0-dev.3.0
```

The first line is the merge that was the basis for our last Dart roll, that is, `e4f708a`. Let's remember that revision (and confirm it):

<pre>$ <strong>git tag last_dart_roll e4f708a</strong>
$ <strong>git rev-parse --short last_dart_roll</strong>
e4f708a</pre>

We can now produce a list of changes that needs to be cherry picked:

<pre>$ <strong>git log --oneline last_dart_roll..origin/_temporary_fletch_patches</strong>
822ff59 Add fletch to task_kill.py
c619107 Shorten and prettify build bot information.
92e3e0d Update download link to use 'proper' URL.
2cb8330 Use correct syntax for STEP_LINK command.
d2c9cd8 Map 'mac' to 'macos'.
14b5d3d Start auto-uploading binaries for the Dart VM to GCS.
257523b First version of the bot script for building the Dart SDK with Fletch-specific patches.
0c39c78 Use vfork instead of fork on Linux.
1c621f6 Unix Domain Sockets
d4f3a89 Remove WATCHLISTS.</pre>

We need to apply these revisions reversed, but "Remove WATCHLISTS." is likely to cause a conflict, so we'll handle that first:

<pre>$ <strong>git cherry-pick d4f3a89</strong></pre>

If there's a conflict, just remove the file and commit the result:

<pre>$ <strong>git rm -f WATCHLISTS</strong>
$ <strong>git commit --no-edit</strong></pre>

You need the rest of the commits in reverse order:

<pre>$ <strong>git log --oneline last_dart_roll..origin/_temporary_fletch_patches | tail -r | tail +2</strong>
1c621f6 Unix Domain Sockets
0c39c78 Use vfork instead of fork on Linux.
257523b First version of the bot script for building the Dart SDK with Fletch-specific patches.
14b5d3d Start auto-uploading binaries for the Dart VM to GCS.
d2c9cd8 Map 'mac' to 'macos'.
2cb8330 Use correct syntax for STEP_LINK command.
92e3e0d Update download link to use 'proper' URL.
c619107 Shorten and prettify build bot information.
822ff59 Add fletch to task_kill.py</pre>

It's best to save the list of commits in a file rather than having two git commands in a pipeline as they both may attempt to get a lock on the repository. So let's say we stored the above commits in a file named `changes.txt`, and edited it to remove any we don't want. We can now run cherry-pick:

<pre>$ <strong>cut -d' '  -f1 changes.txt | xargs git cherry-pick</strong>
[_temporary_fletch_patches 548b92f] Use vfork instead of fork on Linux.
 Date: Thu Jun 18 13:14:37 2015 +0200
 1 file changed, 50 insertions(+), 59 deletions(-)
[_temporary_fletch_patches 40fee5a] First version of the bot script for building the Dart SDK with Fletch-specific patches.
 Author: Kasper Lund <kasperl@google.com>
 Date: Fri Jul 3 11:08:23 2015 +0200
 1 file changed, 46 insertions(+)
 create mode 100644 tools/bots/sdk_fletch_patched.py
[_temporary_fletch_patches 052f3f4] Start auto-uploading binaries for the Dart VM to GCS.
 Author: Kasper Lund <kasperl@google.com>
 Date: Fri Jul 3 13:04:19 2015 +0200
 1 file changed, 17 insertions(+), 8 deletions(-)
[_temporary_fletch_patches 1f13cb8] Map 'mac' to 'macos'.
 Author: Kasper Lund <kasperl@google.com>
 Date: Fri Jul 3 13:39:14 2015 +0200
 1 file changed, 11 insertions(+), 10 deletions(-)
[_temporary_fletch_patches 6afc972] Use correct syntax for STEP_LINK command.
 Author: Kasper Lund <kasperl@google.com>
 Date: Fri Jul 3 14:26:16 2015 +0200
 1 file changed, 1 insertion(+), 1 deletion(-)
[_temporary_fletch_patches 0777e44] Update download link to use 'proper' URL.
 Author: Kasper Lund <kasperl@google.com>
 Date: Fri Jul 3 14:33:00 2015 +0200
 1 file changed, 1 insertion(+), 1 deletion(-)
[_temporary_fletch_patches 715e3d1] Shorten and prettify build bot information.
 Author: Kasper Lund <kasperl@google.com>
 Date: Fri Jul 3 14:44:09 2015 +0200
 1 file changed, 2 insertions(+), 2 deletions(-)
[_temporary_fletch_patches 5020b4b] Add fletch to task_kill.py
 Date: Thu Aug 13 16:19:05 2015 +0200
 1 file changed, 18 insertions(+), 3 deletions(-)
</pre>

In the above example I removed 1c621f6 because I'm testing out a new version of that patch.

## Push the changes

```git push origin _temporary_fletch_patches```

**Comment by kasperl** [comment]
Once you push the changes, we have 3 dart-sdk-fletch-patched-* bots building the patched Dart VM binaries for Mac OS, Linux, and Linux ARM and uploading them to Google Cloud Storage.

Here are examples of the produced binaries:

https://storage.googleapis.com/fletch-archive/91d809c99f6d80b58f5e85782e4bc18f7f9efb53/dart-vm-x64-macos
https://storage.googleapis.com/fletch-archive/91d809c99f6d80b58f5e85782e4bc18f7f9efb53/dart-vm-x64-linux
https://storage.googleapis.com/fletch-archive/91d809c99f6d80b58f5e85782e4bc18f7f9efb53/dart-vm-arm-linux

We may still need to tweak the build settings to make sure the built binaries work in all the settings we need them to work in.

**Comment by skabet** [comment]
Can confirm the output is not glibc compatible for ARM.

**Comment by mkustermann** [comment]
We need to build the dart binary on an ARM machine I think or on a older linux machine if we want to cross compile.

**Comment by peter-ahe-google** [comment]
Fixed in https://github.com/dart-lang/fletch/wiki/Dart-Roll/78edff0974f3fc4f733a0f2f1927d11f5bba6ebe
