### ISSUE TITLE
FFI support for setting in memory is broken on 32 bits

### ISSUE THREAD

**Issue by ricowind** [dart-lang/fletch#64]
What will reproduce the problem:
  Foreign memory = new Foreign.allocated(8);
  var bigint = 9223372036854775806;
  memory.setInt64(0, bigint);
  Expect.equals(memory.getInt64(0), bigint);

Expected result: pass

Actual: 
Uncaught exception:
a Instance: 
  - class = class  - @0 = Expect.equals(expected: <-2>, actual: <9223372036854775806>) fails.

**Comment by skabet** [comment]
Issue 64 is about 64 bit ints... Coincidence...?

**Comment by ricowind** [comment]
Fixed by dd43d2cc4edab43b259ea9a4f053a5188b7123b9
