### ISSUE TITLE
Tests using an old -Xexpose-gc functionality no longer work

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/fletch#76]
The following two tests:

  * tests/unsorted/messaging_drop_messages_test.dart
  * tests/unsorted/messaging_port_lifetime_expose_gc_test.dart

assume to get an extra argument which is a function, when invoked, forces a GC.

In the original code this functionality was enabled by passing `-Xexpose-gc` to the vm, the entry point would then check if we expose the GC and if so pass an additional argument to main (at least that seems to be the original intention):

```dart
// https://codereview.chromium.org/1067873003/diff/20001/lib/system/entry.dart
 14 _entry(int mainArity) {	
 15   if (mainArity == 0) {	
 16     _runToEnd(main);	
 17   } else {	
 18     var arguments = _exposeGC() ? [_gc] : [];	
 19     _runToEnd(() => main(arguments));
```

The native will return true if the flag was set.

```c++
  46 NATIVE(ExposeGC) {
  47   return ToBool(process, Flags::expose_gc);
  48 }
  49 
```

The [CL](https://codereview.chromium.org/1067873003/) seemed to have removed that functionality

**Comment by mit-mit** [comment]
Closing this as part of #50
