### ISSUE TITLE
Crash error could point user directly to Fletch issues

### ISSUE THREAD

**Issue by sethladd** [dart-lang/fletch#78]
Hi,

First off, thanks for using a very user friendly error message when things go wrong.

I wonder if we could point the user straight to https://github.com/dart-lang/fletch/issues/new ?

Right now, it says:

```
The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.
```

**Comment by peter-ahe-google** [comment]
I think this is the error message from dart2js, so I'll close this as a duplicate of issue #87.
