### ISSUE TITLE
language/final_syntax_test/08 is passing for the wrong reason

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/fletch#81]
The test is testing what happens when you have something like this:

```
final A2 = A3 + 1; /// 08: continued
final A3 = A2 + 1; /// 08: continued
```

Eventually, the code generated by fletchc runs out of stack space. This causes the test to pass, however, it should throw a different exception. For example, the Dart VM prints:

```
Reading static variable 'A2' during its initialization
```

**Comment by mit-mit** [comment]
This is part of #71
