### ISSUE TITLE
Update testing of snapshots on build bot

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/fletch#82]
We currently use test.dart -cfletchc -rfletchvm to test snapshots on the build bot. This invokes "fletch compile-and-run" which we would like to get rid of.

In addition, I think there may be a problem testing runtime and compile-time errors using the current approach. We want to test the snapshot in two different modes (without "-Xunfold-program" and with). We schedule three command executions using test.dart infrastructure:

1. fletch compile-and-run -o my_test.dart.snapshot my_test.dart
2. fletch-vm my_test.dart.snapshot
3. fletch-vm -Xunfold-program my_test.dart.snapshot

Here's the problem: if this is a negative test, that for example, expects a runtime error, test.dart will not execute command 3 if command 2 correctly reports an error. Command 3 could have crashed and we would never know.

I believe the solution is to use a custom command like I did in ad08382f2998a6a13e1b00759073a996e0fdcdbb.

**Comment by mit-mit** [comment]
We think this was fixed
