### ISSUE TITLE
Unable to print via 'package:fletchc/fletchc.dart'

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/fletch#86]
At revision 569ac8fd69f2 I seem to be unable to use our `package:fletchc/fletchc.dart` for running normal programs since output from the VM doesn't get printed anymore:

```
$ cat hello.dart
main() {
  print('hello world');
}
$ out/ReleaseIA32/dart -p package package:fletchc/fletchc.dart hello.dart
$ echo $?
0
```

This may be related to the printing changes done recently.

@madsager Could you take a look?

**Comment by madsager** [comment]
Oops, sorry about that. I only register the print interceptor if debugging. I should probably register the print interceptor when we spawn the first process instead so that stdout and stderr is always communicated via the wire protocol to fletchc.
